### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by isha123456** [SNICScienceCloud/LDSA-Spark#4]
Hi,

I missed the lab sessions because of my full-time work. I wonder what passwords we should use.

1. To log in, the instructions are saying to use  ssh core@<floating IP>  
When I do this, I get a prompt to enter the password. What is the  password here?
 
In labs 1 and 2, we used ssh -i <SSH_key> ubuntu<floating IP>. Should I also use the SSH key here?
 
2.        EXPORT_TSP_JUPYTER_TOKEN=<your password>
Which password should I use here? The same as in point 1 above?

I am blocked in lab3 until I get the answers.

**Comment by mcapuccini** [comment]
Hi! You should use the SSH key. You can either use the `-i` option, or you can add the SSH key to the shell session with `ssh-add`. The password that you export is just for Jupyter, it has nothing to do with SSH. Please let me know if you manage!

**Comment by isha123456** [comment]
It is working now.
